######################################################################
# Automatically generated by qmake (2.01a) ? 7? 6 17:09:12 2011
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . ..
INCLUDEPATH += . ..

# Input
HEADERS += Depth_2d_driver.h
SOURCES += Depth_2d_driver.cpp main.cpp
