# src

QMAKE = qmake

all :
	cd Depth_2d_viewer/ && $(QMAKE) && $(MAKE)
	cd Moving_sphere/ && $(MAKE)

clean :
	cd Depth_2d_viewer/ && $(QMAKE) && $(MAKE) distclean
	cd Moving_sphere/ && $(MAKE) clean
